version: '3.7'

services:
  postgres:
    image: "postgres:14"
    restart: always
    shm_size: 256m
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: cXbRyftrqbstH
      POSTGRES_DB: scheduler
    container_name: ps_db

volumes:
  pgdata:
