spring:
  application:
    name: Saas Scheduler
  profiles:
    active: dev
  liquibase:
    change-log: classpath:liquibase/master.xml

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    overwrite-existing-jobs: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /scheduler-saas.html

jwt:
  secret: dXh5bldWUVBJNFhrcFlIckJ0dEF6VnluUGNvUGR3MDY=
  validityInMinutes: 15

# Not for production use
security:
  username: hedza06
  password: hedza123

