### Creating scheduled Job
POST http://localhost:8080/api/job-creator/create
Content-Type: application/json
Authorization: jwt-token-goes-here

{
    "definition": "0 0/10 * * * ?",
    "description": "scheduled-job-name",
    "url": "http://localhost:8080/test",
    "requestPayload": {
        "param1": "value1"
    }
}