### Force run scheduled Http Job
PUT http://localhost:8080/api/job/http/force-run/a38f2230-e5ba-43d3-9572-da90c75e9689
Content-Type: application/json
Authorization: Bearer jwt-token-goes-here

{
    "url": "http://localhost:8080/test",
    "requestBody": {
        "param1": "value1"
    },
    "requestHeaders": {
        "header1": "value1"
    }
}